export const carMakes = [
    "Acura",
    // "Alfa Romeo",
    // "Aston Martin",
    "Audi",
    // "Bentley",
    "BMW",
    "Bugatti",
    // "Buick",
    // "Cadillac",
    "Chevrolet",
    // "Chrysler",
    // "Citroën",
    // "Dodge",
    "Ferrari",
    "Fiat",
    "Ford",
    "Genesis",
    "GMC",
    "Honda",
    "Hyundai",
    "Infiniti",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    // "Lincoln",
    // "Lotus",
    "Maserati",
    "Mazda",
    // "McLaren",
    "Mercedes-Benz",
    "Mini",
    // "Mitsubishi",
    "Nissan",
    "Pagani",
    "Peugeot",
    "Porsche",
    // "Ram",
    "Renault",
    // "Rolls-Royce",
    // "Saab",
    // "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo",
  ];

export const carCategory = [
  "Sedan",
  "SUV",
  "Hatchback",
  "Coupe",
  "Minivan",
  "Crossover",
  "Sports Car",
  "Luxury Car",
  "Wagon",
  "Van",
  "Convertible",
  "City Car",
];