export const carMakes = [
    "Acura",
    // "Alfa Romeo",
    // "Aston Martin",
    "Audi",
    // "Bentley",
    "BMW",
    "Bugatti",
    // "Buick",
    // "Cadillac",
    "Chevrolet",
    // "Chrysler",
    // "Citroën",
    // "Dodge",
    "Ferrari",
    "Fiat",
    "Ford",
    "Genesis",
    "GMC",
    "Honda",
    "Hyundai",
    "Infiniti",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    // "Lincoln",
    // "Lotus",
    "Maserati",
    "Mazda",
    // "McLaren",
    "Mercedes-Benz",
    "Mini",
    // "Mitsubishi",
    "Nissan",
    "Pagani",
    "Peugeot",
    "Porsche",
    // "Ram",
    "Renault",
    // "Rolls-Royce",
    // "Saab",
    // "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo",
  ];

export const carCategory = [
  "Sedan",
  "SUV",
  "Hatchback",
  "Coupe",
  "Minivan",
  "Crossover",
  "Sports Car",
  "Luxury Car",
  "Wagon",
  "Van",
  "Convertible",
  "City Car",
];

export const carSpecs = [
  "360-Degree Camera",
  "Adaptive Cruise Control",
  "Apple CarPlay/Android Auto",
  "Automatic Climate Control",
  "Automatic Emergency Braking",
  "Blind Spot Monitoring",
  "Bluetooth Connectivity",
  "Front Air Bags",
  "Heads-Up Display",
  "Heated Seats",
  "Keyless Entry",
  "Lane Departure Warning",
  "LCD Screens",
  "LED Headlights",
  "Leather Seats",
  "Navigation System",
  "Parking Sensors",
  "Power Adjustable Seats",
  "Premium Sound System",
  "Rearview Camera",
  "Remote Start",
  "Sunroof/Moonroof",
  "Tire Pressure Monitoring",
  "USB Ports",
  "Wireless Charging"
];