import logo1 from '../assets/Logos/brandLogo (1).png';
import logo2 from '../assets/Logos/brandLogo (2).png';
import logo3 from '../assets/Logos/brandLogo (3).png';
import logo4 from '../assets/Logos/brandLogo (4).png';
import logo5 from '../assets/Logos/brandLogo (5).png';
import logo6 from '../assets/Logos/brandLogo (6).png';
import logo7 from '../assets/Logos/brandLogo (7).png';
import logo8 from '../assets/Logos/brandLogo (8).png';
import logo9 from '../assets/Logos/brandLogo (9).png';
import logo10 from '../assets/Logos/brandLogo (10).png';
import logo11 from '../assets/Logos/brandLogo (11).png';
import logo12 from '../assets/Logos/brandLogo (12).png';
import logo13 from '../assets/Logos/brandLogo (13).png';
import logo14 from '../assets/Logos/brandLogo (14).png';
import logo15 from '../assets/Logos/brandLogo (15).png';
import logo16 from '../assets/Logos/brandLogo (16).png';
import logo17 from '../assets/Logos/brandLogo (17).png';
import logo18 from '../assets/Logos/brandLogo (18).png';

export const logos = [logo1, logo2, logo3, logo4, logo5, logo6, logo7, logo8, logo9, logo10, logo11, logo12, logo13, logo14, logo15, logo16, logo17, logo18];